### PR TITLE
Remove a floating box shadow on the main nav header

### PR DESCRIPTION
**Pull request by aprescott**
Without this, there is a very faint line which shouldn't be there, at the bottom of the `.navbar.navbar-default.navbar-fixed-top` element.

You can see it in the middle of these screenshots:

screen shot 2015-12-11 at 17 55 21

screen shot 2015-12-11 at 17 55 25

screen shot 2015-12-11 at 17 55 33

screen shot 2015-12-11 at 17 55 35

### CODE REVIEW

**Comment by aprescott** [comment]
I also noticed that I had to edit `Gemfile` to get Jekyll below version 3.0 in order to generate the site (since I had 3.x installed):

```diff
-gem 'jekyll'
+gem 'jekyll', '< 3.0'
```

Followed by `bundle update jekyll jekyll-sass jekyll-assets`.

**Comment by aprescott** [comment]
If you want, I can fix up the bundle as part of this PR, to get Travis passing.

**Comment by aprescott** [comment]
> there is a very faint line which shouldn't be there

It occurs to me that I don't actually know if it shouldn't be there. :) It looked broken to me, at least. Happy to close this if it's intentional, though.

**Comment by moxie0** [comment]
yeah that was intentional =)

**Comment by aprescott** [comment]
:+1:

**Pull request closed without merging**
